# Generated by Django 3.1.6 on 2021-02-06 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerByMac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17, verbose_name='MAC Address')),
                ('common_name', models.CharField(max_length=100, verbose_name="Manufacturer's Common Name")),
                ('full_name', models.CharField(max_length=100, verbose_name="Manufacturer's Full Name")),
            ],
        ),
        migrations.CreateModel(
            name='NetworkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.GenericIPAddressField(verbose_name='Gateway IP Address')),
                ('active_interface', models.CharField(max_length=50)),
                ('mywirelessIP', models.GenericIPAddressField(verbose_name='Wireless IP Address')),
                ('mywiredIP', models.GenericIPAddressField(verbose_name='Wired IP Address')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('port', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SourceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_child', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SourceSubdomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=100)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctlpanel.source')),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctlpanel.sourcecategory'),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days_of_week', models.CharField(max_length=13)),
                ('is_currently_active', models.BooleanField()),
                ('is_enabled', models.BooleanField()),
                ('action', models.CharField(choices=[('drop_', 'Drop'), ('block', 'Block'), ('allow', 'Allow')], default='block', max_length=5)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctlpanel.source')),
                ('source_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctlpanel.sourcecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctlpanel.user')),
            ],
        ),
        migrations.CreateModel(
            name='DnsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP Address')),
                ('date', models.DateTimeField()),
                ('ttl', models.IntegerField()),
                ('source_subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctlpanel.sourcesubdomain')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17, verbose_name='MAC Address')),
                ('ip', models.CharField(max_length=15, verbose_name='IP Address')),
                ('hostname', models.CharField(max_length=100)),
                ('redirected', models.BooleanField(verbose_name='Controlled Right Now')),
                ('control_level', models.CharField(choices=[('10', 'Red - No Internet Access'), ('5', 'Orange - Some Content Blocked'), ('1', 'Yellow - Adult Content Blocked'), ('0', 'Green - No Content Blocked')], default='0', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctlpanel.user')),
            ],
        ),
    ]
