# Generated by Django 3.1.6 on 2021-02-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctlpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
