# Generated by Django 3.1.6 on 2021-02-06 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctlpanel', '0002_auto_20210206_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcecategory',
            old_name='name',
            new_name='category',
        ),
    ]
