# Generated by Django 3.1.6 on 2021-02-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctlpanel', '0003_auto_20210206_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcecategory',
            old_name='category',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='source',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='source_category',
        ),
        migrations.CreateModel(
            name='SourceFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(blank=True, to='ctlpanel.SourceCategory')),
                ('sources', models.ManyToManyField(blank=True, to='ctlpanel.Source')),
            ],
        ),
        migrations.AddField(
            model_name='rule',
            name='source_filter',
            field=models.ManyToManyField(blank=True, to='ctlpanel.SourceFilter'),
        ),
    ]
